=== openaddresses/openaddresses/schema/source_schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Source",
  "description": "An OpenAddresses source",
  "type": "object",
  "required": [
    "type",
    "data",
    "coverage"
  ],
  "additionalProperties": false,
  "properties": {
    "type": {
      "type": "string",
      "enum": [
        "http",
        "ftp",
        "ESRI"
      ]
    },
    "data": {
      "type": "string"
    },
    "coverage": {
      "$ref": "#/definitions/coverage"
    },
    "website": {
      "type": "string"
    },
    "email": {
      "type": "string",
      "format": "email"
    },
    "conform": {
      "$ref": "#/definitions/conform"
    },
    "compression": {
      "type": "string",
      "enum": ["zip"]
    },
    "license": {
      "oneOf": [
        { "type": "string" },
        { "$ref": "#/definitions/license" }
      ]
    },
    "note": {
      "oneOf": [
        { "type": "string" },
        { "type": "object" }
      ]
    },
    "attribution": {
      "type": "string"
    },
    "language": {
      "type": "string",
      "pattern": "^[a-zA-Z]{2}$"
    },
    "year": {
      "oneOf": [
        { "type": "string" },
        { "type": "integer" }
      ]
    },
    "skip": {
      "type": "boolean"
    },
    "test": {
      "$ref": "#/definitions/test"
    }
  },
  "definitions": {
    "coverage": {
      "type": "object",
      "required": [
        "country"
      ],
      "properties": {
        "country": {
          "type": "string"
        },
        "province": {
          "type": "string"
        },
        "state": {
          "type": "string"
        },
        "county": {
          "type": "string"
        },
        "city": {
          "type": "string"
        },
        "geometry": {
          "$ref": "http://json.schemastore.org/geojson#/definitions/geometry"
        }
      }
    },
    "license": {
      "type": "object",
      "properties": {
        "url": {
          "type": "string",
          "format": "uri"
        },
        "text": {
          "type": "string"
        },
        "attribution": {
          "type": "boolean"
        },
        "attribution name": {
          "type": "string"
        },
        "share-alike": {
          "type": "boolean"
        }
      }
    },
    "base_conform_field_value": {
      "description": "convenience definition for one of null, string, or string array",
      "oneOf": [
        { "type": "null" },
        { "type": "string" },
        {
          "type": "array",
          "minItems": 1,
          "items": { "type": "string" }
        }
      ]
    },
    "conform": {
      "description": "top-level conform object definition",
      "type": "object",
      "required": ["number", "street"],
      "additionalProperties": false,
      "properties": {
        "type": {
          "type": "string",
          "enum": [
            "geojson",
            "shapefile",
            "shapefile-polygon",
            "gdb",
            "xml",
            "csv"
          ]
        },
        "addrtype": {
          "type": "string"
        },
        "accuracy": {
          "description": "https://github.com/openaddresses/openaddresses/blob/master/CONTRIBUTING.md#accuracy",
          "type": "integer",
          "minimum": 0,
          "maximum": 5,
          "exclusiveMinimum": true
        },
        "srs": {
          "type": "string",
          "regex": "EPSG:[0-9]+"
        },
        "file": {
          "type": "string"
        },
        "layer": {
          "description": "specifies a layer to use in the GDB",
          "oneOf": [
            { "type": "integer" },
            { "type": "string" }
          ]
        },
        "encoding": {
          "type": "string"
        },
        "csvsplit": {
          "type": "string"
        },
        "headers": {
          "type": "integer",
          "minimum": -1
        },
        "skiplines": {
          "type": "integer",
          "minimum": 1
        },
        "notes": {
          "type": "string"
        },
        "id": {
          "description": "unique identifier for the address row",
          "oneOf": [
            { "$ref": "#/definitions/base_conform_field_value" },
            { "$ref": "#/definitions/function_regexp" },
            { "$ref": "#/definitions/function_remove_prefix" },
            { "$ref": "#/definitions/function_remove_postfix" },
            { "$ref": "#/definitions/function_join" },
            { "$ref": "#/definitions/function_format" }
          ]
        },
        "number": {
          "description": "the house number for the address row",
          "oneOf": [
            { "$ref": "#/definitions/base_conform_field_value" },
            { "$ref": "#/definitions/function_regexp" },
            { "$ref": "#/definitions/function_prefixed_number" },
            { "$ref": "#/definitions/function_remove_prefix" },
            { "$ref": "#/definitions/function_remove_postfix" },
            { "$ref": "#/definitions/function_join" },
            { "$ref": "#/definitions/function_format" }
          ]
        },
        "street": {
          "description": "the street/road for the address row",
          "oneOf": [
            { "$ref": "#/definitions/base_conform_field_value" },
            { "$ref": "#/definitions/function_regexp" },
            { "$ref": "#/definitions/function_postfixed_street" },
            { "$ref": "#/definitions/function_remove_prefix" },
            { "$ref": "#/definitions/function_remove_postfix" },
            { "$ref": "#/definitions/function_join" },
            { "$ref": "#/definitions/function_format" }
          ]
        },
        "unit": {
          "description": "the suite/unit/apartment for the address row",
          "oneOf": [
            { "$ref": "#/definitions/base_conform_field_value" },
            { "$ref": "#/definitions/function_regexp" },
            { "$ref": "#/definitions/function_remove_prefix" },
            { "$ref": "#/definitions/function_remove_postfix" },
            { "$ref": "#/definitions/function_join" },
            { "$ref": "#/definitions/function_format" }
          ]
        },
        "city": {
          "description": "the city/locality for the address row",
          "oneOf": [
            { "$ref": "#/definitions/base_conform_field_value" },
            { "$ref": "#/definitions/function_regexp" },
            { "$ref": "#/definitions/function_remove_prefix" },
            { "$ref": "#/definitions/function_remove_postfix" },
            { "$ref": "#/definitions/function_join" },
            { "$ref": "#/definitions/function_format" }
          ]
        },
        "district": {
          "description": "the county for the address row",
          "oneOf": [
            { "$ref": "#/definitions/base_conform_field_value" },
            { "$ref": "#/definitions/function_regexp" },
            { "$ref": "#/definitions/function_remove_prefix" },
            { "$ref": "#/definitions/function_remove_postfix" },
            { "$ref": "#/definitions/function_join" },
            { "$ref": "#/definitions/function_format" }
          ]
        },
        "region": {
          "description": "the state/province for the address row",
          "oneOf": [
            { "$ref": "#/definitions/base_conform_field_value" },
            { "$ref": "#/definitions/function_regexp" },
            { "$ref": "#/definitions/function_remove_prefix" },
            { "$ref": "#/definitions/function_remove_postfix" },
            { "$ref": "#/definitions/function_join" },
            { "$ref": "#/definitions/function_format" }
          ]
        },
        "postcode": {
          "description": "the postcode for the address row",
          "oneOf": [
            { "$ref": "#/definitions/base_conform_field_value" },
            { "$ref": "#/definitions/function_regexp" },
            { "$ref": "#/definitions/function_remove_prefix" },
            { "$ref": "#/definitions/function_remove_postfix" },
            { "$ref": "#/definitions/function_join" },
            { "$ref": "#/definitions/function_format" }
          ]
        },
        "lon": {
          "description": "longitude value for the address row, only applies to CSV sources",
          "oneOf": [
            { "type": "null" },
            { "type": "string" },
            { "$ref": "#/definitions/function_regexp" }
          ]
        },
        "lat": {
          "description": "latitude value for the address row, only applies to CSV sources",
          "oneOf": [
            { "type": "null" },
            { "type": "string" },
            { "$ref": "#/definitions/function_regexp" }
          ]
        }
      }
    },
    "test": {
      "description": "test definition",
      "type": "object",
      "required": ["description"],
      "additionalProperties": false,
      "properties": {
        "enabled": {
          "type": "boolean"
        },
        "description": {
          "type": "string"
        },
        "acceptance-tests": {
          "type": "array",
          "minItems": 1,
          "items": { "$ref": "#/definitions/acceptance-test" }
        }
      }
    },
    "acceptance-test": {
      "description": "acceptance-test definition",
      "type": "object",
      "required": ["description", "inputs", "expected"],
      "additionalProperties": false,
      "properties": {
        "description": {
          "type": "string"
        },
        "inputs": {
          "type": "object"
        },
        "expected": {
          "type": "object"
        }
      }
    },
    "function_regexp": {
      "description": "regexp function definition",
      "type": "object",
      "required": ["function", "field", "pattern"],
      "additionalProperties": false,
      "properties": {
        "function": {
          "type": "string",
          "enum": ["regexp"]
        },
        "field": {
          "type": "string"
        },
        "pattern": {
          "type": "string",
          "format": "string"
        },
        "replace": {
          "type": "string"
        }
      }
    },
    "function_prefixed_number": {
      "description": "prefixed_number function definition",
      "type": "object",
      "required": ["function", "field"],
      "additionalProperties": false,
      "properties": {
        "function": {
          "type": "string",
          "enum": ["prefixed_number"]
        },
        "field": {
          "type": "string"
        }
      }
    },
    "function_postfixed_street": {
      "description": "postfixed_street function definition",
      "type": "object",
      "required": ["function", "field"],
      "additionalProperties": false,
      "properties": {
        "function": {
          "type": "string",
          "enum": ["postfixed_street"]
        },
        "field": {
          "type": "string"
        }
      }
    },
    "function_remove_prefix": {
      "description": "remove_prefix function definition",
      "type": "object",
      "required": ["function", "field", "field_to_remove"],
      "additionalProperties": false,
      "properties": {
        "function": {
          "type": "string",
          "enum": ["remove_prefix"]
        },
        "field": {
          "type": "string"
        },
        "field_to_remove": {
          "type": "string"
        }
      }
    },
    "function_remove_postfix": {
      "description": "remove_postfix function definition",
      "type": "object",
      "required": ["function", "field", "field_to_remove"],
      "additionalProperties": false,
      "properties": {
        "function": {
          "type": "string",
          "enum": ["remove_postfix"]
        },
        "field": {
          "type": "string"
        },
        "field_to_remove": {
          "type": "string"
        }
      }
    },
    "function_join": {
      "description": "join function definition",
      "type": "object",
      "required": ["function", "fields"],
      "additionalProperties": false,
      "properties": {
        "function": {
          "type": "string",
          "enum": ["join"]
        },
        "fields": {
          "type": "array",
          "minItems": 1,
          "items": { "type": "string" }
        },
        "separator": {
          "type": "string"
        }
      }
    },
    "function_format": {
      "description": "format function definition",
      "type": "object",
      "required": ["function", "fields", "format"],
      "additionalProperties": false,
      "properties": {
        "function": {
          "type": "string",
          "enum": ["format"]
        },
        "fields": {
          "type": "array",
          "minItems": 1,
          "items": { "type": "string" }
        },
        "format": {
          "type": "string"
        }
      }
    }
  }
}

=== openaddresses/openaddresses/sources/us/tx/ellis.json
{
    "coverage": {
        "US Census": {"geoid": "48139", "name": "Ellis County", "state": "Texas"},
        "country": "us",
        "state": "tx",
        "county": "Ellis"
    },
    "data": "http://mapsatbis.com/bisgis/rest/services/EllisWeb/MapServer/0",
    "type": "ESRI",
    "conform": {
        "number": "EllisCad.DBO.Accounts.situs_num",
        "street": [
            "EllisCad.DBO.Accounts.situs_street_prefx",
            "EllisCad.DBO.Accounts.situs_street",
            "EllisCad.DBO.Accounts.situs_street_sufix"
        ],
        "city": "EllisCad.DBO.Accounts.situs_city",
        "region": "EllisCad.DBO.Accounts.situs_state",
        "postcode": "EllisCad.DBO.Accounts.situs_zip",
        "type": "geojson"
    }
}

=== openaddresses/openaddresses/sources/us-co-pueblo.json
{
    "coverage": {
        "US Census": {
            "geoid": "08101",
            "name": "Pueblo County",
            "state": "Colorado"
        },
        "country": "us",
        "state": "co",
        "county": "Pueblo"
    },
    "attribution": "Pubelo County",
    "data": "http://maps.co.pueblo.co.us/outside/rest/services/pueblo_county_address_points/MapServer/0",
    "type": "ESRI",
    "conform": {
        "type": "csv",
        "lon": "x",
        "lat": "y",
        "number": "ADDRNUM",
        "street": "STNAME",
        "postcode": "ZIP",
        "city": "CITY",
        "region": "STATE",
        "accuracy": 1
    }
}

=== openaddresses/openaddresses/sources/us/ia/webster.json
{
  "coverage": {
    "US Census": {
      "geoid": "19187",
      "name": "Webster County",
      "state": "Iowa"
    },
    "country": "us",
    "state": "ia",
    "county": "Webster"
  },
  "data": "ftp://ftp.igsb.uiowa.edu/gis_library/counties/Webster/Address_94.zip",
  "license": {
    "text": "Public Domain",
    "attribution": false,
    "share-alike": false
  },
  "year": "2012?",
  "type": "ftp",
  "compression": "zip",
  "conform": {
    "number": {
      "function": "regexp",
      "field": "address",
      "pattern": "^([0-9]+)"
    },
    "street": {
      "function": "regexp",
      "field": "address",
      "pattern": "^(?:[0-9]+ )(.*)",
      "replace": "$1"
    },
    "type": "shapefile"
  }
}

=== openaddresses/openaddresses/sources/us/ri/us-ri.json
{
    "coverage": {
        "US Census": {"geoid": "44", "state": "Rhode Island"},
        "country": "us",
        "state": "ri"
    },
    "website": "http://www.edc.uri.edu/rigis/data/data.aspx?ISO=structure",
    "data": "http://www.edc.uri.edu/rigis/spfdata/structure/e911Sites15r1.zip",
    "license": "http://www.edc.uri.edu/rigis/license.html",
    "type": "http",
    "compression": "zip",
    "conform": {
        "type": "shapefile",
        "lon": "x",
        "lat": "y",
        "number": "HouseNumbe",
        "street": "PrimaryNam",
        "city": "ZN",
        "postcode": "Zip"
    }
}

=== openaddresses/openaddresses/sources/us-ks-thomas_county.json
{
    "coverage": {
        "US Census": {
            "geoid": "20193",
            "name": "Thomas County",
            "state": "Kansas"
        },
        "country": "us",
        "state": "ks",
        "county": "Thomas"
    },
    "conform": {
        "type": "csv",
        "number": "add_",
        "street": "street",
        "postcode": "zip",
        "lon": "x",
        "lat": "y"
    },
    "data": "http://72.205.198.131/ArcGIS/rest/services/Thomas/Thomas/MapServer/30",
    "type": "ESRI"
}

=== openaddresses/openaddresses/sources/us-al-tuscaloosa.json
{
    "coverage": {
        "US Census": {
            "geoid": "01125",
            "name": "Tuscaloosa County",
            "state": "Alabama"
        },
        "country": "us",
        "state": "al",
        "county": "Tuscaloosa"
    },
    "type": "ESRI",
    "data": "http://services1.arcgis.com/DADyRNMb7tdzKmmq/arcgis/rest/services/Addresses/FeatureServer/0",
    "conform": {
        "type": "csv",
        "lat": "OA:y",
        "lon": "OA:x",
        "number": "HNUM",
        "street": "STREET",
        "city": "POSTAL_CIT",
        "postcode": "ZIP"
    }
}

=== openaddresses/openaddresses/sources/us/ct/ct.json
{
    "coverage": {
        "US Census": {"geoid": "09", "state": "Connecticut"},
        "country": "us",
        "state": "ct"
    },
    "conform": {
        "type": "csv",
        "number": "CompleteAddressNumber",
        "street": "CompleteStreetName",
        "postcode": "ZipCode",
        "city": "Municipal_PlaceName",
        "region": "County_PlaceName",
        "lon": "OA:x",
        "lat": "OA:y"
    },
    "data": "http://www.ctgismaps2.ct.gov/arcgis/rest/services/CT_Open_Maps/Address_Points/MapServer/0",
    "type": "ESRI"
}

=== openaddresses/openaddresses/sources/us/oh/morrow.json
{
    "coverage": {
        "US Census": {
            "geoid": "39117",
            "name": "Morrow County",
            "state": "Ohio"
        },
        "country": "us",
        "state": "oh",
        "county": "Morrow"
    },
    "data": "http://gis3.oit.ohio.gov/LBRS/_downloads/MRW_ADDS.zip",
    "type": "http",
    "compression": "zip",
    "conform": {
        "number": "HOUSENUM",
        "street": [
            "ST_PREFIX",
            "ST_NAME",
            "ST_TYPE",
            "ST_SUFFIX"
        ],
        "type": "shapefile",
        "postcode": "zipcode"
    }
}
