=== openaddresses/openaddresses/schema/source_schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Source",
  "description": "An OpenAddresses source",
  "type": "object",
  "required": [
    "type",
    "data",
    "coverage"
  ],
  "additionalProperties": false,
  "properties": {
    "type": {
      "type": "string",
      "enum": [
        "http",
        "ftp",
        "ESRI"
      ]
    },
    "data": {
      "type": "string"
    },
    "coverage": {
      "$ref": "#/definitions/coverage"
    },
    "website": {
      "type": "string"
    },
    "email": {
      "type": "string",
      "format": "email"
    },
    "conform": {
      "$ref": "#/definitions/conform"
    },
    "compression": {
      "type": "string",
      "enum": ["zip"]
    },
    "license": {
      "oneOf": [
        { "type": "string" },
        { "$ref": "#/definitions/license" }
      ]
    },
    "note": {
      "oneOf": [
        { "type": "string" },
        { "type": "object" }
      ]
    },
    "attribution": {
      "type": "string"
    },
    "language": {
      "type": "string",
      "pattern": "^[a-zA-Z]{2}$"
    },
    "year": {
      "oneOf": [
        { "type": "string" },
        { "type": "integer" }
      ]
    },
    "skip": {
      "type": "boolean"
    },
    "test": {
      "$ref": "#/definitions/test"
    }
  },
  "definitions": {
    "coverage": {
      "type": "object",
      "required": [
        "country"
      ],
      "properties": {
        "country": {
          "type": "string"
        },
        "province": {
          "type": "string"
        },
        "state": {
          "type": "string"
        },
        "county": {
          "type": "string"
        },
        "city": {
          "type": "string"
        },
        "geometry": {
          "$ref": "http://json.schemastore.org/geojson#/definitions/geometry"
        }
      }
    },
    "license": {
      "type": "object",
      "properties": {
        "url": {
          "type": "string",
          "format": "uri"
        },
        "text": {
          "type": "string"
        },
        "attribution": {
          "type": "boolean"
        },
        "attribution name": {
          "type": "string"
        },
        "share-alike": {
          "type": "boolean"
        }
      }
    },
    "base_conform_field_value": {
      "description": "convenience definition for one of null, string, or string array",
      "oneOf": [
        { "type": "null" },
        { "type": "string" },
        {
          "type": "array",
          "minItems": 1,
          "items": { "type": "string" }
        }
      ]
    },
    "conform": {
      "description": "top-level conform object definition",
      "type": "object",
      "required": ["number", "street"],
      "additionalProperties": false,
      "properties": {
        "type": {
          "type": "string",
          "enum": [
            "geojson",
            "shapefile",
            "shapefile-polygon",
            "gdb",
            "xml",
            "csv"
          ]
        },
        "addrtype": {
          "type": "string"
        },
        "accuracy": {
          "description": "https://github.com/openaddresses/openaddresses/blob/master/CONTRIBUTING.md#accuracy",
          "type": "integer",
          "minimum": 0,
          "maximum": 5,
          "exclusiveMinimum": true
        },
        "srs": {
          "type": "string",
          "regex": "EPSG:[0-9]+"
        },
        "file": {
          "type": "string"
        },
        "layer": {
          "description": "specifies a layer to use in the GDB",
          "oneOf": [
            { "type": "integer" },
            { "type": "string" }
          ]
        },
        "encoding": {
          "type": "string"
        },
        "csvsplit": {
          "type": "string"
        },
        "headers": {
          "type": "integer",
          "minimum": -1
        },
        "skiplines": {
          "type": "integer",
          "minimum": 1
        },
        "notes": {
          "type": "string"
        },
        "id": {
          "description": "unique identifier for the address row",
          "oneOf": [
            { "$ref": "#/definitions/base_conform_field_value" },
            { "$ref": "#/definitions/function_regexp" },
            { "$ref": "#/definitions/function_remove_prefix" },
            { "$ref": "#/definitions/function_remove_postfix" },
            { "$ref": "#/definitions/function_join" },
            { "$ref": "#/definitions/function_format" }
          ]
        },
        "number": {
          "description": "the house number for the address row",
          "oneOf": [
            { "$ref": "#/definitions/base_conform_field_value" },
            { "$ref": "#/definitions/function_regexp" },
            { "$ref": "#/definitions/function_prefixed_number" },
            { "$ref": "#/definitions/function_remove_prefix" },
            { "$ref": "#/definitions/function_remove_postfix" },
            { "$ref": "#/definitions/function_join" },
            { "$ref": "#/definitions/function_format" }
          ]
        },
        "street": {
          "description": "the street/road for the address row",
          "oneOf": [
            { "$ref": "#/definitions/base_conform_field_value" },
            { "$ref": "#/definitions/function_regexp" },
            { "$ref": "#/definitions/function_postfixed_street" },
            { "$ref": "#/definitions/function_remove_prefix" },
            { "$ref": "#/definitions/function_remove_postfix" },
            { "$ref": "#/definitions/function_join" },
            { "$ref": "#/definitions/function_format" }
          ]
        },
        "unit": {
          "description": "the suite/unit/apartment for the address row",
          "oneOf": [
            { "$ref": "#/definitions/base_conform_field_value" },
            { "$ref": "#/definitions/function_regexp" },
            { "$ref": "#/definitions/function_remove_prefix" },
            { "$ref": "#/definitions/function_remove_postfix" },
            { "$ref": "#/definitions/function_join" },
            { "$ref": "#/definitions/function_format" }
          ]
        },
        "city": {
          "description": "the city/locality for the address row",
          "oneOf": [
            { "$ref": "#/definitions/base_conform_field_value" },
            { "$ref": "#/definitions/function_regexp" },
            { "$ref": "#/definitions/function_remove_prefix" },
            { "$ref": "#/definitions/function_remove_postfix" },
            { "$ref": "#/definitions/function_join" },
            { "$ref": "#/definitions/function_format" }
          ]
        },
        "district": {
          "description": "the county for the address row",
          "oneOf": [
            { "$ref": "#/definitions/base_conform_field_value" },
            { "$ref": "#/definitions/function_regexp" },
            { "$ref": "#/definitions/function_remove_prefix" },
            { "$ref": "#/definitions/function_remove_postfix" },
            { "$ref": "#/definitions/function_join" },
            { "$ref": "#/definitions/function_format" }
          ]
        },
        "region": {
          "description": "the state/province for the address row",
          "oneOf": [
            { "$ref": "#/definitions/base_conform_field_value" },
            { "$ref": "#/definitions/function_regexp" },
            { "$ref": "#/definitions/function_remove_prefix" },
            { "$ref": "#/definitions/function_remove_postfix" },
            { "$ref": "#/definitions/function_join" },
            { "$ref": "#/definitions/function_format" }
          ]
        },
        "postcode": {
          "description": "the postcode for the address row",
          "oneOf": [
            { "$ref": "#/definitions/base_conform_field_value" },
            { "$ref": "#/definitions/function_regexp" },
            { "$ref": "#/definitions/function_remove_prefix" },
            { "$ref": "#/definitions/function_remove_postfix" },
            { "$ref": "#/definitions/function_join" },
            { "$ref": "#/definitions/function_format" }
          ]
        },
        "lon": {
          "description": "longitude value for the address row, only applies to CSV sources",
          "oneOf": [
            { "type": "null" },
            { "type": "string" },
            { "$ref": "#/definitions/function_regexp" }
          ]
        },
        "lat": {
          "description": "latitude value for the address row, only applies to CSV sources",
          "oneOf": [
            { "type": "null" },
            { "type": "string" },
            { "$ref": "#/definitions/function_regexp" }
          ]
        }
      }
    },
    "test": {
      "description": "test definition",
      "type": "object",
      "required": ["description"],
      "additionalProperties": false,
      "properties": {
        "enabled": {
          "type": "boolean"
        },
        "description": {
          "type": "string"
        },
        "acceptance-tests": {
          "type": "array",
          "minItems": 1,
          "items": { "$ref": "#/definitions/acceptance-test" }
        }
      }
    },
    "acceptance-test": {
      "description": "acceptance-test definition",
      "type": "object",
      "required": ["description", "inputs", "expected"],
      "additionalProperties": false,
      "properties": {
        "description": {
          "type": "string"
        },
        "inputs": {
          "type": "object"
        },
        "expected": {
          "type": "object"
        }
      }
    },
    "function_regexp": {
      "description": "regexp function definition",
      "type": "object",
      "required": ["function", "field", "pattern"],
      "additionalProperties": false,
      "properties": {
        "function": {
          "type": "string",
          "enum": ["regexp"]
        },
        "field": {
          "type": "string"
        },
        "pattern": {
          "type": "string",
          "format": "string"
        },
        "replace": {
          "type": "string"
        }
      }
    },
    "function_prefixed_number": {
      "description": "prefixed_number function definition",
      "type": "object",
      "required": ["function", "field"],
      "additionalProperties": false,
      "properties": {
        "function": {
          "type": "string",
          "enum": ["prefixed_number"]
        },
        "field": {
          "type": "string"
        }
      }
    },
    "function_postfixed_street": {
      "description": "postfixed_street function definition",
      "type": "object",
      "required": ["function", "field"],
      "additionalProperties": false,
      "properties": {
        "function": {
          "type": "string",
          "enum": ["postfixed_street"]
        },
        "field": {
          "type": "string"
        }
      }
    },
    "function_remove_prefix": {
      "description": "remove_prefix function definition",
      "type": "object",
      "required": ["function", "field", "field_to_remove"],
      "additionalProperties": false,
      "properties": {
        "function": {
          "type": "string",
          "enum": ["remove_prefix"]
        },
        "field": {
          "type": "string"
        },
        "field_to_remove": {
          "type": "string"
        }
      }
    },
    "function_remove_postfix": {
      "description": "remove_postfix function definition",
      "type": "object",
      "required": ["function", "field", "field_to_remove"],
      "additionalProperties": false,
      "properties": {
        "function": {
          "type": "string",
          "enum": ["remove_postfix"]
        },
        "field": {
          "type": "string"
        },
        "field_to_remove": {
          "type": "string"
        }
      }
    },
    "function_join": {
      "description": "join function definition",
      "type": "object",
      "required": ["function", "fields"],
      "additionalProperties": false,
      "properties": {
        "function": {
          "type": "string",
          "enum": ["join"]
        },
        "fields": {
          "type": "array",
          "minItems": 1,
          "items": { "type": "string" }
        },
        "separator": {
          "type": "string"
        }
      }
    },
    "function_format": {
      "description": "format function definition",
      "type": "object",
      "required": ["function", "fields", "format"],
      "additionalProperties": false,
      "properties": {
        "function": {
          "type": "string",
          "enum": ["format"]
        },
        "fields": {
          "type": "array",
          "minItems": 1,
          "items": { "type": "string" }
        },
        "format": {
          "type": "string"
        }
      }
    }
  }
}

=== openaddresses/openaddresses/sources/us/ca/us-ca-marin_county.json
{
    "coverage": {
        "US Census": {
            "geoid": "06041",
            "name": "Marin County",
            "state": "California"
        },
        "country": "us",
        "state": "ca",
        "county": "Marin"
    },
    "attribution": "Marlin County",
    "data": "http://gis.marinpublic.com/arcgis/rest/services/BaseMap/DistrictService/MapServer/0",
    "type": "ESRI",
    "conform": {
        "lon": "x",
        "lat": "y",
        "number": "number",
        "street": [
            "PreDir",
            "street",
            "suffix",
            "PostDir"
        ],
        "type": "csv",
        "postcode": "zipcode"
    }
}

=== openaddresses/openaddresses/sources/us/ne/polk.json
{
    "coverage": {
        "US Census": {
            "geoid": "31143",
            "name": "Polk County",
            "state": "Nebraska"
        },
        "country": "us",
        "state": "ne",
        "county": "Polk"
    },
    "data": "http://maps6.gisworkshop.com/ArcGIS/rest/services/Polk/MapServer/1",
    "type": "ESRI",
    "conform": {
        "type": "geojson",
        "number": {
            "function": "regexp",
            "field": "PROPADDRESS",
            "pattern": "^([0-9]+)"
        },
        "street": {
            "function": "regexp",
            "field": "PROPADDRESS",
            "pattern": "^(?:[0-9]+ )(.*)",
            "replace": "$1"
        }
    }
}

=== openaddresses/openaddresses/sources/us/tx/gaines.json
{
    "coverage": {
        "US Census": {"geoid": "48165", "name": "Gaines County", "state": "Texas"},
        "country": "us",
        "state": "tx",
        "county": "Gaines"
    },
    "data": "http://mapsatbis.com/bisgis/rest/services/GainesWeb/MapServer/0",
    "type": "ESRI",
    "conform": {
        "number": "GainesCad.DBO.Accounts.situs_num",
        "street": [
            "GainesCad.DBO.Accounts.situs_street_prefx",
            "GainesCad.DBO.Accounts.situs_street",
            "GainesCad.DBO.Accounts.situs_street_sufix"
        ],
        "city": "GainesCad.DBO.Accounts.situs_city",
        "region": "GainesCad.DBO.Accounts.situs_state",
        "postcode": "GainesCad.DBO.Accounts.situs_zip",
        "type": "geojson"
    }
}

=== openaddresses/openaddresses/sources/us/fl/us-fl-collier.json
{
    "coverage": {
        "US Census": {
            "geoid": "12021",
            "name": "Collier County",
            "state": "Florida"
        },
        "country": "us",
        "state": "fl",
        "county": "Collier"
    },
    "attribution": "Collier County",
    "data": "https://apps3.colliergov.net/downloads/siteaddresspoint.zip",
    "website": "http://www.colliergov.net/Index.aspx?page=2713",
    "license": "Public Domain",
    "type": "http",
    "compression": "zip",
    "conform": {
        "type": "shapefile",
        "lon": "x",
        "lat": "y",
        "number": "ADDRNUM",
        "street": "FULLNAME",
        "city": "MUNICIPALI"
    }
}

=== openaddresses/openaddresses/sources/us/wa/us-wa-mason.json
{
    "coverage": {
        "US Census": {
            "geoid": "53045",
            "name": "Mason County",
            "state": "Washington"
        },
        "country": "us",
        "state": "wa",
        "county": "Mason"
    },
    "license": "http://www.co.mason.wa.us/gis/disclaimer.php",
    "type": "ESRI",
    "compression": "zip",
    "note": "point shapefile Site_Address.shp, address columns: ADDRESS, ZIP_CD",
    "year": "2014",
    "data": "http://www.arcgis.com/home/item.html?id=986434ffd63b4c7ba618953d5e049ae9",
    "website": "http://www.co.mason.wa.us/gis/"
}

=== openaddresses/openaddresses/sources/us/tx/collin.json
{
    "coverage": {
        "US Census": {
            "geoid": "48085",
            "name": "Collin County",
            "state": "Texas"
        },
        "country": "us",
        "state": "tx",
        "county": "Collin"
    },
    "data": "http://gismaps.collincountytx.gov/ArcGIS/rest/services/dynamic/AddressPoints/MapServer/0",
    "type": "ESRI",
    "conform": {
        "type": "geojson",
        "street": [
            "ADD_PRE",
            "ADD_NAME",
            "ADD_TYPE",
            "ADD_SUF"
        ],
        "number": "ADD_NUMBER"
    }
}

=== openaddresses/openaddresses/sources/us/mo/us-mo-barry.json
{
    "coverage": {
        "US Census": {
            "geoid": "29009",
            "name": "Barry County",
            "state": "Missouri"
        },
        "country": "us",
        "state": "mo",
        "county": "Barry"
    },
    "data": "http://gis-server.greatriv.com/ArcGIS/rest/services/BarryCo/BarryCo_operational/MapServer/2",
    "type": "ESRI",
    "conform": {
        "lon": "x",
        "lat": "y",
        "number": "address",
        "street": "roadname",
        "type": "geojson"
    }
}

=== openaddresses/openaddresses/sources/ca/ab/city_of_chestermere.json
{
    "coverage": {
        "country": "ca",
        "state": "ab",
        "city": "Chestermere",
        "geometry": { "type": "Point", "coordinates": [-113.853, 51.030] }
    },
    "data": "https://services3.arcgis.com/8FWoKvthx3zWyrPO/ArcGIS/rest/services/Chestermere_Address_Points/FeatureServer/0",
    "type": "ESRI",
    "conform": {
        "type": "geojson",
        "id": "FID",
        "number": "ADDRESS_HO",
        "unit": "ADDRESS_AP",
        "street": "ADDRESS_ST"
    }
}
