=== openaddresses/openaddresses/schema/source_schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Source",
  "description": "An OpenAddresses source",
  "type": "object",
  "required": [
    "type",
    "data",
    "coverage"
  ],
  "additionalProperties": false,
  "properties": {
    "type": {
      "type": "string",
      "enum": [
        "http",
        "ftp",
        "ESRI"
      ]
    },
    "data": {
      "type": "string"
    },
    "coverage": {
      "$ref": "#/definitions/coverage"
    },
    "website": {
      "type": "string"
    },
    "email": {
      "type": "string",
      "format": "email"
    },
    "conform": {
      "$ref": "#/definitions/conform"
    },
    "compression": {
      "type": "string",
      "enum": ["zip"]
    },
    "license": {
      "oneOf": [
        { "type": "string" },
        { "$ref": "#/definitions/license" }
      ]
    },
    "note": {
      "oneOf": [
        { "type": "string" },
        { "type": "object" }
      ]
    },
    "attribution": {
      "type": "string"
    },
    "language": {
      "type": "string",
      "pattern": "^[a-zA-Z]{2}$"
    },
    "year": {
      "oneOf": [
        { "type": "string" },
        { "type": "integer" }
      ]
    },
    "skip": {
      "type": "boolean"
    },
    "test": {
      "$ref": "#/definitions/test"
    }
  },
  "definitions": {
    "coverage": {
      "type": "object",
      "required": [
        "country"
      ],
      "properties": {
        "country": {
          "type": "string"
        },
        "province": {
          "type": "string"
        },
        "state": {
          "type": "string"
        },
        "county": {
          "type": "string"
        },
        "city": {
          "type": "string"
        },
        "geometry": {
          "$ref": "http://json.schemastore.org/geojson#/definitions/geometry"
        }
      }
    },
    "license": {
      "type": "object",
      "properties": {
        "url": {
          "type": "string",
          "format": "uri"
        },
        "text": {
          "type": "string"
        },
        "attribution": {
          "type": "boolean"
        },
        "attribution name": {
          "type": "string"
        },
        "share-alike": {
          "type": "boolean"
        }
      }
    },
    "base_conform_field_value": {
      "description": "convenience definition for one of null, string, or string array",
      "oneOf": [
        { "type": "null" },
        { "type": "string" },
        {
          "type": "array",
          "minItems": 1,
          "items": { "type": "string" }
        }
      ]
    },
    "conform": {
      "description": "top-level conform object definition",
      "type": "object",
      "required": ["number", "street"],
      "additionalProperties": false,
      "properties": {
        "type": {
          "type": "string",
          "enum": [
            "geojson",
            "shapefile",
            "shapefile-polygon",
            "gdb",
            "xml",
            "csv"
          ]
        },
        "addrtype": {
          "type": "string"
        },
        "accuracy": {
          "description": "https://github.com/openaddresses/openaddresses/blob/master/CONTRIBUTING.md#accuracy",
          "type": "integer",
          "minimum": 0,
          "maximum": 5,
          "exclusiveMinimum": true
        },
        "srs": {
          "type": "string",
          "regex": "EPSG:[0-9]+"
        },
        "file": {
          "type": "string"
        },
        "layer": {
          "description": "specifies a layer to use in the GDB",
          "oneOf": [
            { "type": "integer" },
            { "type": "string" }
          ]
        },
        "encoding": {
          "type": "string"
        },
        "csvsplit": {
          "type": "string"
        },
        "headers": {
          "type": "integer",
          "minimum": -1
        },
        "skiplines": {
          "type": "integer",
          "minimum": 1
        },
        "notes": {
          "type": "string"
        },
        "id": {
          "description": "unique identifier for the address row",
          "oneOf": [
            { "$ref": "#/definitions/base_conform_field_value" },
            { "$ref": "#/definitions/function_regexp" },
            { "$ref": "#/definitions/function_remove_prefix" },
            { "$ref": "#/definitions/function_remove_postfix" },
            { "$ref": "#/definitions/function_join" },
            { "$ref": "#/definitions/function_format" }
          ]
        },
        "number": {
          "description": "the house number for the address row",
          "oneOf": [
            { "$ref": "#/definitions/base_conform_field_value" },
            { "$ref": "#/definitions/function_regexp" },
            { "$ref": "#/definitions/function_prefixed_number" },
            { "$ref": "#/definitions/function_remove_prefix" },
            { "$ref": "#/definitions/function_remove_postfix" },
            { "$ref": "#/definitions/function_join" },
            { "$ref": "#/definitions/function_format" }
          ]
        },
        "street": {
          "description": "the street/road for the address row",
          "oneOf": [
            { "$ref": "#/definitions/base_conform_field_value" },
            { "$ref": "#/definitions/function_regexp" },
            { "$ref": "#/definitions/function_postfixed_street" },
            { "$ref": "#/definitions/function_remove_prefix" },
            { "$ref": "#/definitions/function_remove_postfix" },
            { "$ref": "#/definitions/function_join" },
            { "$ref": "#/definitions/function_format" }
          ]
        },
        "unit": {
          "description": "the suite/unit/apartment for the address row",
          "oneOf": [
            { "$ref": "#/definitions/base_conform_field_value" },
            { "$ref": "#/definitions/function_regexp" },
            { "$ref": "#/definitions/function_remove_prefix" },
            { "$ref": "#/definitions/function_remove_postfix" },
            { "$ref": "#/definitions/function_join" },
            { "$ref": "#/definitions/function_format" }
          ]
        },
        "city": {
          "description": "the city/locality for the address row",
          "oneOf": [
            { "$ref": "#/definitions/base_conform_field_value" },
            { "$ref": "#/definitions/function_regexp" },
            { "$ref": "#/definitions/function_remove_prefix" },
            { "$ref": "#/definitions/function_remove_postfix" },
            { "$ref": "#/definitions/function_join" },
            { "$ref": "#/definitions/function_format" }
          ]
        },
        "district": {
          "description": "the county for the address row",
          "oneOf": [
            { "$ref": "#/definitions/base_conform_field_value" },
            { "$ref": "#/definitions/function_regexp" },
            { "$ref": "#/definitions/function_remove_prefix" },
            { "$ref": "#/definitions/function_remove_postfix" },
            { "$ref": "#/definitions/function_join" },
            { "$ref": "#/definitions/function_format" }
          ]
        },
        "region": {
          "description": "the state/province for the address row",
          "oneOf": [
            { "$ref": "#/definitions/base_conform_field_value" },
            { "$ref": "#/definitions/function_regexp" },
            { "$ref": "#/definitions/function_remove_prefix" },
            { "$ref": "#/definitions/function_remove_postfix" },
            { "$ref": "#/definitions/function_join" },
            { "$ref": "#/definitions/function_format" }
          ]
        },
        "postcode": {
          "description": "the postcode for the address row",
          "oneOf": [
            { "$ref": "#/definitions/base_conform_field_value" },
            { "$ref": "#/definitions/function_regexp" },
            { "$ref": "#/definitions/function_remove_prefix" },
            { "$ref": "#/definitions/function_remove_postfix" },
            { "$ref": "#/definitions/function_join" },
            { "$ref": "#/definitions/function_format" }
          ]
        },
        "lon": {
          "description": "longitude value for the address row, only applies to CSV sources",
          "oneOf": [
            { "type": "null" },
            { "type": "string" },
            { "$ref": "#/definitions/function_regexp" }
          ]
        },
        "lat": {
          "description": "latitude value for the address row, only applies to CSV sources",
          "oneOf": [
            { "type": "null" },
            { "type": "string" },
            { "$ref": "#/definitions/function_regexp" }
          ]
        }
      }
    },
    "test": {
      "description": "test definition",
      "type": "object",
      "required": ["description"],
      "additionalProperties": false,
      "properties": {
        "enabled": {
          "type": "boolean"
        },
        "description": {
          "type": "string"
        },
        "acceptance-tests": {
          "type": "array",
          "minItems": 1,
          "items": { "$ref": "#/definitions/acceptance-test" }
        }
      }
    },
    "acceptance-test": {
      "description": "acceptance-test definition",
      "type": "object",
      "required": ["description", "inputs", "expected"],
      "additionalProperties": false,
      "properties": {
        "description": {
          "type": "string"
        },
        "inputs": {
          "type": "object"
        },
        "expected": {
          "type": "object"
        }
      }
    },
    "function_regexp": {
      "description": "regexp function definition",
      "type": "object",
      "required": ["function", "field", "pattern"],
      "additionalProperties": false,
      "properties": {
        "function": {
          "type": "string",
          "enum": ["regexp"]
        },
        "field": {
          "type": "string"
        },
        "pattern": {
          "type": "string",
          "format": "string"
        },
        "replace": {
          "type": "string"
        }
      }
    },
    "function_prefixed_number": {
      "description": "prefixed_number function definition",
      "type": "object",
      "required": ["function", "field"],
      "additionalProperties": false,
      "properties": {
        "function": {
          "type": "string",
          "enum": ["prefixed_number"]
        },
        "field": {
          "type": "string"
        }
      }
    },
    "function_postfixed_street": {
      "description": "postfixed_street function definition",
      "type": "object",
      "required": ["function", "field"],
      "additionalProperties": false,
      "properties": {
        "function": {
          "type": "string",
          "enum": ["postfixed_street"]
        },
        "field": {
          "type": "string"
        }
      }
    },
    "function_remove_prefix": {
      "description": "remove_prefix function definition",
      "type": "object",
      "required": ["function", "field", "field_to_remove"],
      "additionalProperties": false,
      "properties": {
        "function": {
          "type": "string",
          "enum": ["remove_prefix"]
        },
        "field": {
          "type": "string"
        },
        "field_to_remove": {
          "type": "string"
        }
      }
    },
    "function_remove_postfix": {
      "description": "remove_postfix function definition",
      "type": "object",
      "required": ["function", "field", "field_to_remove"],
      "additionalProperties": false,
      "properties": {
        "function": {
          "type": "string",
          "enum": ["remove_postfix"]
        },
        "field": {
          "type": "string"
        },
        "field_to_remove": {
          "type": "string"
        }
      }
    },
    "function_join": {
      "description": "join function definition",
      "type": "object",
      "required": ["function", "fields"],
      "additionalProperties": false,
      "properties": {
        "function": {
          "type": "string",
          "enum": ["join"]
        },
        "fields": {
          "type": "array",
          "minItems": 1,
          "items": { "type": "string" }
        },
        "separator": {
          "type": "string"
        }
      }
    },
    "function_format": {
      "description": "format function definition",
      "type": "object",
      "required": ["function", "fields", "format"],
      "additionalProperties": false,
      "properties": {
        "function": {
          "type": "string",
          "enum": ["format"]
        },
        "fields": {
          "type": "array",
          "minItems": 1,
          "items": { "type": "string" }
        },
        "format": {
          "type": "string"
        }
      }
    }
  }
}

=== openaddresses/openaddresses/sources/us/tx/us-tx-keller.json
{
    "coverage": {
        "country": "us",
        "state": "tx",
        "city": "Keller"
    },
    "data": "http://gis.dfwmaps.com/ArcGIS/rest/services/Keller/Keller_All_VE/MapServer/13",
    "type": "ESRI",
    "conform": {
        "lon": "x",
        "lat": "y",
        "number": "STREETNUMB",
        "street": [
            "STREETNAME",
            "STREETTYPE"
        ],
        "type": "geojson"
    }
}

=== openaddresses/openaddresses/sources/us/va/us-va-amherst.json
{
    "coverage": {
        "US Census": {
            "geoid": "51009",
            "name": "Amherst County",
            "state": "Virginia"
        },
        "country": "us",
        "state": "va",
        "county": "Amherst"
    },
    "data": "http://vcloud.timmons.com/ArcGIS/rest/services/Amherst/Amherst_Weblogistics/MapServer/1",
    "type": "ESRI",
    "website": "http://amherstgis.timmons.com/",
    "conform": {
        "lon": "x",
        "lat": "y",
        "number": "address",
        "street": "roadname",
        "type": "geojson"
    }
}

=== openaddresses/openaddresses/sources/us/nc/nash.json
{
    "coverage": {
        "US Census": {"geoid": "37127", "name": "Nash County", "state": "North Carolina"},
        "country": "us",
        "state": "nc",
        "county": "Nash"
    },
    "data": "http://data.nconemap.gov/downloads/vector/parcels/Nash_parcels_2017_09_19.zip",
    "type": "http",
    "compression": "zip",
    "website": "http://data.nconemap.gov/geoportal/catalog/search/resource/details.page?uuid=%7B837C5704-49C8-45A3-B084-AEBF4CD09804%7D",
    "conform": {
        "type": "shapefile",
        "file": "nc_nash_parcels_pt_2017_09_19.shp",
        "id": "PARNO",
        "number": {
            "function": "prefixed_number",
            "field": "SITEADD"
        },
        "street": {
            "function": "postfixed_street",
            "field": "SITEADD"
        }
    }
}

=== openaddresses/openaddresses/sources/mx/pue/statewide.json
{
    "website": "http://busca.datos.gob.mx/#/conjuntos/directorio-estadistico-nacional-de-unidades-economicas-denue-por-entidad-federativa",
    "conform": {
        "city": "Municipio",
        "street": "Nombre de la vialidad",
        "region": "Puebla",
        "lon": "Longitud",
        "number": "Número exterior o kilómetro",
        "postcode": "Código Postal",
        "lat": "Latitud",
        "type": "csv"
    },
    "attribution": "Source: INEGI, Directorio Estadístico Nacional de Unidades Económicas (DENUE)",
    "compression": "zip",
    "license": {
        "url": "http://datos.gob.mx/libreusomx/",
        "attribution": true,
        "share-alike": false
    },
    "data": "http://www3.inegi.org.mx/sistemas/descarga/descargaarchivo.aspx?file=DENUE%2fEntidad_federativa%2f21_Puebla%2fdenue_21_25022015_csv.zip",
    "coverage": {
        "ISO 3166": {
            "alpha2": "MX-PUE",
            "country": "Mexico",
            "state": "Puebla"
        },
        "country": "mx"
    },
    "type": "http"
}

=== openaddresses/openaddresses/sources/us/oh/scioto.json
{
    "coverage": {
        "US Census": {
            "geoid": "39145",
            "name": "Scioto County",
            "state": "Ohio"
        },
        "country": "us",
        "state": "oh",
        "county": "Scioto"
    },
    "data": "https://www.sciotocountyengineer.org/arcgis/rest/services/OneView/ParcelsSearch/MapServer/0/1",
    "type": "ESRI",
    "conform": {
        "type": "geojson",
        "number": "LocStrNo",
        "street": [
            "LocStrDir",
            "LocStrName",
            "LocStrSuffix"
        ],
        "unit": "LocStrNo2",
        "city": "LocCity",
        "region": "LocState",
        "postcode": "LocZipCode"
    }
}

=== openaddresses/openaddresses/sources/us/mt/missoula.json
{
  "coverage": {
    "US Census": {
      "geoid": "30063",
      "name": "Missoula County",
      "state": "Montana"
    },
    "country": "us",
    "state": "mt",
    "county": "Missoula"
  },
  "data": "ftp://anonymous:anonymous@ftp.gis.mt.gov/CadastralFramework/Missoula/MissoulaOwnerParcel_shp.zip",
  "type": "ftp",
  "compression": "zip",
  "conform": {
    "number": {
      "function": "regexp",
      "field": "AddressLin",
      "pattern": "^([0-9]+)"
    },
    "street": {
      "function": "regexp",
      "field": "AddressLin",
      "pattern": "^(?:[0-9]+ )(.*)",
      "replace": "$1"
    },
    "type": "shapefile-polygon",
    "accuracy": 2
  }
}

=== openaddresses/openaddresses/sources/ca/ab/city_of_red_deer.json
{
    "coverage": {
        "country": "ca",
        "state": "ab",
        "city": "Red Deer",
        "geometry": {
            "type": "Point",
            "coordinates": [
                -113.802,
                52.26682
            ]
        }
    },
    "data": "http://maps.rdcounty.ca:6080/arcgis/rest/services/RDC_ArcGIS_Base_Map/MapServer/8",
    "type": "ESRI",
    "conform": {
        "type": "geojson",
        "number": "HOUSE_ID",
        "street": [
            "DIR_PREF",
            "NAME_PREF",
            "MAIN_NAME",
            "ROAD_TYPE",
            "DIR_SUFX"
        ],
        "unit": "UNIT_NUM"
    }
}

=== openaddresses/openaddresses/sources/us/ks/shawnee_county.json
{
  "coverage": {
    "US Census": {
      "geoid": "20177",
      "name": "Shawnee County",
      "state": "Kansas"
    },
    "country": "us",
    "state": "ks",
    "county": "Shawnee"
  },
  "conform": {
    "type": "geojson",
    "number": "HOUSENUM",
    "street": {
      "function": "regexp",
      "field": "PADDRESS",
      "pattern": "^(?:[0-9]+ )(.*)",
      "replace": "$1"
    },
    "postcode": "ZipCode"
  },
  "data": "http://gis.snco.us/ArcGIS/rest/services/Basemap_102100/MapServer/1",
  "type": "ESRI"
}
